services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-chatbot-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://book_user:123456@postgres:5432/book_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg17
    container_name: library-chatbot-postgres
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: library-chatbot-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
